version: '3.8'
services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
  nodejs-backend:
    build: .
    stdin_open: true
    tty: true
    ports:
      - '4000:4000'
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    depends_on:
      - postgres
