version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: /Dockerfile.database
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  nodejs-backend:
    build:
      context: .
      dockerfile: /Dockerfile.server
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    restart: always
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - PORT=3000
      - PASS=${PASS}
    depends_on:
      postgres:
          condition: service_healthy
